name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependências
        working-directory: backend
        run: npm install

      - name: Executar testes
        working-directory: backend
        run: npm test

    env:
      JWT_SECRET_KEY: 'senha-secreta'
      ADMIN_PASSWORD: '123456'
      ADMIN_EMAIL: 'adm@adm.com'